### ISSUE TITLE
[Investigation] See if release could be automated

### ISSUE THREAD

**Issue by gderaco** [Backbase/variants#186]
Investigation about automation of brew release pipeline, including building bottles and linking them to the formulae

**Comment by arthurpalves** [comment]
This has been done in our [Tap](https://github.com/Backbase/homebrew-m/blob/master/.github/workflows/manual_release.yaml)

**Comment by jenskuhrjorgensen** [comment]
Hi @arthurpalves 

We have some issues installing the `variants` tool via our Homebrew Artifactory proxy and I believe it might be caused because your package is not available in the [Homebrew Formulae](https://formulae.brew.sh/formula/). I'm not a Homebrew expert so I don't know why it is not visible in the formulae list or how much work it would take to get it there. All I can see is that even though I specify `HOMEBREW_ARTIFACT_DOMAIN` it still tries to install the package directly from GitHub instead of our private Artifactory. This is the command and error I receive (because my company policy doesn't allow downloading certain file formats from the internet without going through our Artifactory):

```
user % HOMEBREW_ARTIFACT_DOMAIN=... brew install variants
==> Fetching backbase/m/variants
==> Downloading https://github.com/Backbase/homebrew-m/releases/download/1.2.1/variants-1.2.1.arm64_monterey.bottle.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/271573302/77504ff6-7152-4533-8d22-51144823fa62?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVCODYLSA53PQK4Z
############################################################################################################################################################################################################### 100.0%curl: (22) The requested URL returned error: 403

Error: variants: Failed to download resource "variants"
Download failed: https://github.com/Backbase/homebrew-m/releases/download/1.2.1/variants-1.2.1.arm64_monterey.bottle.tar.gz
```

**Comment by arthurpalves** [comment]
Hi @jenskuhrjorgensen,
Sorry for the late reply.

> your package is not available in the [Homebrew Formulae](https://formulae.brew.sh/formula/)

We want to maintain our own tap instead, hence the installation requires us to specify the tap `backbase/m`.

> it still tries to install the package directly from GitHub instead of our private Artifactory.

I see that it tries to install a bottle (a pre built package with a binary). This is to make installation faster by not building it from the source. The bottle has been pre built during the release and stored here https://github.com/Backbase/homebrew-m/releases/download/1.2.1/. I believe (but could be wrong) that if you try to force it to build from source it would work fine in your case:

```
brew install backbase/m/variants --build-from-source
```

**Comment by jenskuhrjorgensen** [comment]
@arthurpalves that worked - thanks a lot! 😀

**Comment by arthurpalves** [comment]
@jenskuhrjorgensen Awesome. Don't hesitate to open a new issue if you need help with anything.
