### ISSUE TITLE
Unable to install Variant v1.1.0 using brew

### ISSUE THREAD

**Issue by vaibhavmBB** [Backbase/variants#190]
When brew install is provided version, it fails to install the latest version (v1.1.0). Instead, it throws the following error:
```
vaibhavm@bb-system-2148 variants-1.0.0 % brew install backbase/m/variants@1.1.0
==> Downloading https://github.com/Backbase/variants/releases/download/1.1.0/var
curl: (22) The requested URL returned error: 404                

Error: variants@1.1.0: Failed to download resource "variants@1.1.0"
Download failed: https://github.com/Backbase/variants/releases/download/1.1.0/variants%401.1.0-1.1.0.monterey.bottle.tar.gz
```

**Comment by arthurpalves** [comment]
The issue is resolved for future versions with the automated release. It generates bottles for the given version and duplicates the files explicitly specifying the version in the filenames.

Unfortunately, for version 1.1.0 the issue will persist, so installation needs to be done by forcing a build from source:
```bash
brew install variants@1.1.0 --build-from-source
```
